--- !ruby/object:Library
authors: &25
- &1 !ruby/object:Author
  name: name1
  biography: biography1
- &4 !ruby/object:Author
  name: name2
  biography: biography2
- &7 !ruby/object:Author
  name: name3
  biography: biography3
- &9 !ruby/object:Author
  name: name4
  biography: biography4
- &11 !ruby/object:Author
  name: name1
  biography: biography1
- &14 !ruby/object:Author
  name: name2
  biography: biography2
- &17 !ruby/object:Author
  name: name3
  biography: biography3
- &19 !ruby/object:Author
  name: name4
  biography: biography4
readers: &26
- &2 !ruby/object:Reader
  name: reader1
  email: reader1@reader.ua
  city: dnepr
  street: reader1street
  house: '2'
- &5 !ruby/object:Reader
  name: reader2
  email: reader2@reader.ua
  city: dnepr
  street: reader2street
  house: '1'
- &8 !ruby/object:Reader
  name: reader3
  email: reader3@reader.ua
  city: kiev
  street: reader3street
  house: '37'
- &10 !ruby/object:Reader
  name: reader4
  email: reader4@reader.ua
  city: cherkasy
  street: reader4street
  house: '17'
- &12 !ruby/object:Reader
  name: reader1
  email: reader1@reader.ua
  city: dnepr
  street: reader1street
  house: '2'
- &15 !ruby/object:Reader
  name: reader2
  email: reader2@reader.ua
  city: dnepr
  street: reader2street
  house: '1'
- &18 !ruby/object:Reader
  name: reader3
  email: reader3@reader.ua
  city: kiev
  street: reader3street
  house: '37'
- &20 !ruby/object:Reader
  name: reader4
  email: reader4@reader.ua
  city: cherkasy
  street: reader4street
  house: '17'
orders: &27
- !ruby/object:Order
  book: &3 !ruby/object:Book
    title: book1
    author: *1
  reader: *2
  date: 10:09:27 15-10-2015
- !ruby/object:Order
  book: *3
  reader: *2
  date: 10:09:27 15-10-2015
- !ruby/object:Order
  book: *3
  reader: *2
  date: 10:09:27 15-10-2015
- !ruby/object:Order
  book: &6 !ruby/object:Book
    title: book2
    author: *4
  reader: *5
  date: 10:09:27 15-10-2015
- !ruby/object:Order
  book: *6
  reader: *5
  date: 10:09:27 15-10-2015
- !ruby/object:Order
  book: &21 !ruby/object:Book
    title: book3
    author: *7
  reader: *8
  date: 10:09:27 15-10-2015
- !ruby/object:Order
  book: &22 !ruby/object:Book
    title: book4
    author: *9
  reader: *10
  date: 10:09:27 15-10-2015
- !ruby/object:Order
  book: &13 !ruby/object:Book
    title: book1
    author: *11
  reader: *12
  date: 10:12:24 15-10-2015
- !ruby/object:Order
  book: *13
  reader: *12
  date: 10:12:24 15-10-2015
- !ruby/object:Order
  book: *13
  reader: *12
  date: 10:12:24 15-10-2015
- !ruby/object:Order
  book: &16 !ruby/object:Book
    title: book2
    author: *14
  reader: *15
  date: 10:12:24 15-10-2015
- !ruby/object:Order
  book: *16
  reader: *15
  date: 10:12:24 15-10-2015
- !ruby/object:Order
  book: &23 !ruby/object:Book
    title: book3
    author: *17
  reader: *18
  date: 10:12:24 15-10-2015
- !ruby/object:Order
  book: &24 !ruby/object:Book
    title: book4
    author: *19
  reader: *20
  date: 10:12:24 15-10-2015
books: &28
- *3
- *6
- *21
- *22
- *13
- *16
- *23
- *24
hash:
  book1: 6
  book2: 4
  book3: 2
  book4: 2
read: !ruby/object:Library
  authors: *25
  readers: *26
  orders: *27
  books: *28
  hash:
    book1: 3
    book2: 2
    book3: 1
    book4: 1
